### PR TITLE
Added required suffix for custom completion rule in 4.3+

### LINKED ISSUE #140: 4.3 suffix
```
And I set the field "Course completion tertiary navigation" to "Default activity completion": debugging() message/s found:
Custom completion rule completionattendance of module facetoface has wrong suffix and has been removed from the form. This has to be fixed by the developer
line 126 of /completion/classes/edit_base_form.php: call to debugging()
line 148 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_custom_completion()
line 178 of /completion/classes/form/form_trait.php: call to core_completion_edit_base_form->add_completion_rules()
line 249 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_completion_elements()
line 118 of /completion/classes/defaultedit_form.php: call to core_completion_edit_base_form->definition()
line 217 of /lib/formslib.php: call to core_completion_defaultedit_form->definition()
line 45 of /completion/classes/defaultedit_form.php: call to moodleform->__construct()
line 89 of /course/classes/output/bulk_activity_completion_renderer.php: call to core_completion_defaultedit_form->__construct()
line 97 of /course/defaultcompletion.php: call to core_course_bulk_activity_completion_renderer->defaultcompletion()
```

### PR DESCRIPTION
**Pull request by opitz**
Added a suffix to the custom completion rule in mod_form.php.
This will fix #140.

### CODE REVIEW

**Comment by danmarsden** [comment]
Thanks @opitz  - our typical preference is to create a new branch instead of writing if version X do Y type code as it increases technical debt.

If you get a chance, feel free to update the PR so that it just includes the changes required for 4.3 - feel free to make the pr against our MOODE_400_STABLE branch and we'll create a new 4.3 branch to merge it into.

thanks!

**Comment by opitz** [comment]
@danmarsden fixed now (or so I hope...).

**Comment by danmarsden** [comment]
thanks - I've created a new 4.3 branch and merged that in!

**Comment by danmarsden** [comment]
looks like we still have some behat failures on the 4.3 branch, hopefully someone will get a chance to look at those sometime

**Pull request merged**
