### PR TITLE
Adding multi-search/delimited search

### PR DESCRIPTION
**Pull request by vedantnayar**
Using the | character, users can search the list of attendees for multiple users at the same time. Particularly useful when the list of users is huge, to avoid needing to enrol users one at a time.

Recommendation: Works well with the Excel TEXTJOIN() function

Contributions by @chalhoub-university, @geoffreyvanwyk and me

### CODE REVIEW

**Comment by danmarsden** [comment]
Thanks for the PR - my initial instinct (without looking closely) would be that this sounds wrong as I can't think of any other instance in Moodle core where a search is done in a similar way. If the page is hard to manage with multiple users, there are probably other ways to improve the UX without building in "hidden features" like this..

**Comment by vedantnayar** [comment]
Hi Dan,
This works well for our team's use case, but I'd definitely like to hear of the right way to implement this so we can make improvements so that it's more useful to everyone. Cheers!

**Comment by danmarsden** [comment]
from memory, I think this is using the same UI as the manage site roles page - it might be better to look at moving towards something more like the enrol users UI or somehow use some similar UX to the new moodle 4.0 reportbuilder API, but ideally we'd get Moodle to improve the UX of a core component and then copy that within F2F - 
Moodle 4.0 has some new reportbuilder apis with various pop-out filters - would be nice if you could apply various filters to the list of users being displayed, but it really depends on the use-case here..

Of course - if you manage to get something like "|" supported in the moodle core manage site roles page, we could then add the same behaviour into the F2F version of the plugin too.

**Comment by danmarsden** [comment]
one option would be to add a new "search option" checkbox that enable multi-search for searcing with any individual word - eg if the checkbox was ticked a search of "dan amy" was entered it would find all users with "dan" and all users with "amy" 

Also - anything like this being added would likely need unit tests to test the new behaviour too.

**Comment by danmarsden** [comment]
closing this one as won't fix for now - but feel free to resubmit if you are able to improve the implementation as mentioned above - thanks!

**Pull request closed without merging**
